workflows:
  android-workflow:
    name: Build Direct App APK
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Clean and Regenerate Fresh Android Project
        script: |
          rm -rf android
          flutter create . --platforms=android --org=com.example --template=app
      - name: Get packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
