workflows:
  android-workflow:
    name: Build Direct App APK
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Generate Android Skeleton
        script: |
          mkdir temp_app
          cd temp_app
          flutter create . --platforms=android --org=com.example
          cp -R android ..
          cd ..
          rm -rf temp_app
      - name: Get packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
